
#QUESTÃO 1


# valor1 = int(input("Digite 0 ou 1: ")) 
# valor2 = int(input("Digite para o segundo valor: 0 ou 1 "))
# valor3 = int(input("Digite para o terceiro valor : 0 ou 1 "))

# if valor1 and valor2 or valor3:
#     print("verdadeiro")
# else:
#     print("falso")


#-------------------------------------------------------------------
    
#QUESTÃO 2
    
numero_do_usuario = int(input("Digite um número qualquer: "))

for i in range (0, numero_do_usuario +1 ):
    if i % 2 == 0:  
        print(i)
 
#--------------------------------------------------------------------